name: Build

on: workflow_dispatch

jobs:
  deploy:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Get Npcap Sdk
        run: |
          curl https://npcap.com/dist/npcap-sdk-1.13.zip -o sdk.zip
          unzip sdk.zip

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          LIB: ${{ github.workspace }}/Lib/x64/

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: stardb-exporter.zip
          path: target/release/stardb-exporter.exe
