name: Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  deploy:
    name: Release
    runs-on: windows-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Get Npcap Sdk
        run: |
          curl https://npcap.com/dist/npcap-sdk-1.13.zip -o sdk.zip
          unzip sdk.zip

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          LIB: ${{ github.workspace }}/Lib/x64/

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest Release
          files: target/release/stardb-exporter.exe
